### ISSUE TITLE
Dynamic Line Not Supported Error not allowing character creation

### ISSUE THREAD

**Issue by Ravor9933** [Noctifer-de-Mortem/nocts_cata_mod#108] opened 2019-06-28 20:39 UTC
DEBUG    : Error: data/mods//nocts_cata_mod-0.D/Npc/TALK_MSCI.json: line 72:7: dynamic line not supported

 Apophis...  It was a Bio-Weapon specifically designed to eliminate every other Bio-Weapon and Bio-Weapon scientist.  Now we can try to get things fixed up eventually, and work on research that might benefit others out there."
      }
    },
      ^
    "responses": [
      { "text": "Oh, good luck, I suppose.", "topic": "TALK_MSCI" },
      {

 
 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 709

Running latest experimental build of the game

**Comment by chaosvolt** [comment] 2019-06-30 13:04
Update your mod as well as the build, then re-test.

**Comment by chaosvolt** [comment] 2019-06-30 23:08
Any luck? Because that error was fixed by https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/88. 90% odds you're using the launcher, which REQUIRES you to manually re-download mods yourself last I checked (and is the cause of way too many bugs being reported that were fixed ages ago).

**Closed by chaosvolt** 2019-06-30 23:08 UTC

**Comment by Ravor9933** [comment] 2019-07-03 18:07
Yeah, that's what happened, thank you for your help!
